server:
  port: 8282
  servlet:
    encoding:
      charset: UTF-8
      force: true
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/learnblog?useSSL=true&useUnicode=true&charset=utf8&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: test
    password: 12345678
    type: com.alibaba.druid.pool.DruidDataSource
    # druid 数据源专有配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true

    #配置监控统计拦截的filters，stat:监控统计、wall：防御sql注入
    filters: stat,wall
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500


  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: true
    properties:
      open-entity-manager-in-view: true

  # 设置序列化的时间区间
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss

  # 设置数据迁移版本控制
  flyway:
    enabled: true
    encoding: UTF-8
    locations: classpath:/db/migration/
    check-location: true
    connect-retries: 5

  # 视图模板设置为freemarker
  freemarker:
    template-loader-path: classpath:/templates/
    check-template-location: true
    suffix: .ftl
    cache: false
    settings:
      classic_compatible: true #处理空值
      template_exception_handler: rethrow
      template_update_delay: 0
      datetime_format: yyyy-MM-dd HH:mm
      number_format: 0.##

  # 设置静态资源目录
  mvc:
    static-path-pattern: /static/**

  output:
    ansi:
      enabled: always

  # 简单配置 Redis
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
    timeout: 5000ms
    lettuce:
      pool:
        max-active: 100
        max-idle: 20
        min-idle: 0
        max-wait: 30000ms

  # 设置MongoDB
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/learnblog

# 设置mybatis
mybatis:
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  type-aliases-package: com.bp.learnblog.entity.mybatis

# 设置 log
logging:
  level:
    root: info
  file:
    path: "D:\\dockerworkspace\\workspace\\learning\\java\\projects\\learnblog\\target\\logs"
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
    file: "[%level] %date [%thread] %logger{20}.%M %L :%m%n"
