
# 用户表
DROP TABLE IF EXISTS user;
CREATE TABLE user (
    id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
    username VARCHAR(30) NOT NULL UNIQUE COMMENT '用户名（唯一）',
    real_name VARCHAR(50) COMMENT '真实姓名',
    password VARCHAR(255) NOT NULL COMMENT '密码',
    salt VARBINARY(255) COMMENT '盐',
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    INDEX username_index (`username`) USING BTREE
) ENGINE = INNODB DEFAULT CHARSET = UTF8 COLLATE UTF8_UNICODE_CI COMMENT '用户表';

# 角色表
DROP TABLE IF EXISTS role;
CREATE TABLE role (
    id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
    name VARCHAR(30) NOT NULL UNIQUE COMMENT '角色名称',
    description VARCHAR(255) NOT NULL DEFAULT '' COMMENT '描述',
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`)
) ENGINE = INNODB DEFAULT CHARSET = UTF8 COLLATE UTF8_UNICODE_CI COMMENT '角色表';

# 权限表
DROP TABLE IF EXISTS permission;
CREATE TABLE permission (
    id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
    name VARCHAR(30) NOT NULL UNIQUE COMMENT '权限名称',
    description VARCHAR(255) NOT NULL DEFAULT '' COMMENT '描述',
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`)
) ENGINE = INNODB DEFAULT CHARSET = UTF8 COLLATE UTF8_UNICODE_CI COMMENT '权限表';

# 用户角色表
DROP TABLE IF EXISTS user_role;
CREATE TABLE user_role (
    user_id BIGINT(20),
    role_id BIGINT(20),
    FOREIGN KEY (`user_id`) REFERENCES user(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`role_id`) REFERENCES role(`id`) ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = UTF8 COLLATE UTF8_UNICODE_CI COMMENT '用户角色关联表';

# 角色权限表
DROP TABLE IF EXISTS role_permission;
CREATE TABLE role_permission (
    role_id BIGINT(20),
    permission_id BIGINT(20),
    FOREIGN KEY (`role_id`) REFERENCES role(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`permission_id`) REFERENCES permission(`id`) ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = UTF8 COLLATE UTF8_UNICODE_CI COMMENT '角色权限关联表';