
# 博客文章表
DROP TABLE IF EXISTS `post`;
CREATE TABLE `post` (
    id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
    title VARCHAR(255) NOT NULL COMMENT '博客标题',
    content LONGTEXT COMMENT '内容',
    description VARCHAR(255) COMMENT '描述',
    user_id BIGINT(20) DEFAULT NULL COMMENT '用户id',
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    FOREIGN KEY (`user_id`) REFERENCES user(`id`) ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = UTF8 COLLATE UTF8_UNICODE_CI COMMENT '博客文章表';

# 博客分类表
DROP TABLE IF EXISTS `category`;
CREATE TABLE `category` (
    id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
    name VARCHAR(50) NOT NULL COMMENT '分类名称',
    description VARCHAR(255) COMMENT '描述说明',
    user_id BIGINT(20) DEFAULT NULL COMMENT '用户id',
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    FOREIGN KEY (`user_id`) REFERENCES user(`id`) ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = UTF8 COLLATE UTF8_UNICODE_CI COMMENT '博客分类表';

# 博客标签表
DROP TABLE IF EXISTS `tag`;
CREATE TABLE `tag` (
    id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
    name VARCHAR(50) NOT NULL COMMENT '标签名称',
    description VARCHAR(255) COMMENT '描述说明',
    user_id BIGINT(20) DEFAULT NULL COMMENT '用户id',
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    FOREIGN KEY (`user_id`) REFERENCES user(`id`) ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = UTF8 COLLATE UTF8_UNICODE_CI COMMENT '博客标签表';

# 博客评价表
DROP TABLE IF EXISTS `comment`;
CREATE TABLE `comment` (
    id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
    name VARCHAR(50) DEFAULT '' COMMENT '评论标题',
    content LONGTEXT COMMENT '评价内容',
    user_id BIGINT(20) DEFAULT NULL COMMENT '用户id',
    post_id BIGINT(20) DEFAULT NULL COMMENT '博客id',
    parent_id BIGINT(20) DEFAULT NULL COMMENT '评价回复父ID',
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    FOREIGN KEY (`user_id`) REFERENCES user(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`post_id`) REFERENCES post(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`parent_id`) REFERENCES comment(`id`) ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = UTF8 COLLATE UTF8_UNICODE_CI COMMENT '博客评价表';

# 博客文章类别关联表
DROP TABLE IF EXISTS `post_category`;
CREATE TABLE `post_category` (
    post_id BIGINT(20),
    category_id BIGINT(20),
    FOREIGN KEY (`post_id`) REFERENCES post(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`category_id`) REFERENCES category(`id`) ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = UTF8 COLLATE UTF8_UNICODE_CI COMMENT '博客文章类别关联表';

# 博客文章标签关联表
DROP TABLE IF EXISTS `post_tag`;
CREATE TABLE `post_tag` (
    post_id BIGINT(20),
    tag_id BIGINT(20),
    FOREIGN KEY (`post_id`) REFERENCES post(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`tag_id`) REFERENCES tag(`id`) ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = UTF8 COLLATE UTF8_UNICODE_CI COMMENT '博客文章标签关联表';